version: "2"
services:
  beacon:
    build:
      context: beacon_backend/
    # Backend will be reachable at http://127.0.0.1:9075/
    ports:
      - "9075:9075"
    links:
      - beacon_db:beacon_db
    depends_on:
      - beacon_db
  beacon_db:
    build:
      context: beacon_db/
    environment:
      POSTGRES_USER: microaccounts_dev
      POSTGRES_PASSWORD: r783qjkldDsiu
      POSTGRES_DB: elixir_beacon_dev
  beacon_ui:
    build:
      context: beacon_ui/
    ports:
      - "80:80"

